# Generated by Django 3.2.4 on 2023-12-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(help_text='姓名', max_length=255, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.BooleanField(default=1, help_text='性别', verbose_name='性别'),
        ),
    ]
